#- name: echo
#  shell: echo hello
- include_tasks: "{{ ansible_distribution }}/install-buildenvironment.yml"
- name: Copying modules-it-sw.sh
  copy:
    src: /data/ecrc-modules/v2/modules/deploy-scripts/modules-it-sw.sh
    dest: /etc/profile.d
- name: Copying modules-ecrc.sh
  copy:
    src: /data/ecrc-modules/v2/modules/deploy-scripts/modules-ecrc.sh
    dest: /etc/profile.d
