---
# vars file for ecrc-access-restriction
privileged_users:
  - gonzalea
  - ltaiefh
  - a-gonzalea

# List of users who should be granted access
# (rc-ecrc) is an IT defined linux group.
access_users:
  - (rc-ecrc)
  - abdelkr
  - abdullsm
  - akbudak
  - alhartna
  - alonaza
  - alturktl
  - boukarw
  - caninim
  - dalcin
  - doucetn
  - farhanma
  - gaol
  - gonzalea
  - hongy
  - hongy0a
  - keyesde
  - liy0h
  - ltaiefh
  - mikhala
  - omairyrm
  - peterdb
  - reynani
  - sukkarde
  - x_doucetn
  - x_etiennv
  - zampins

# List of users who are NOT ALLOWED to login to ecrc machines
forbidden_users:
  - username1
  - username2
